# # config/redis.yml
# default:
#   host: localhost
#   port: 6379
#   driver: hiredis

# development:
#   db: 0
#   namespace: app_development

# test:
#   db: 1
#   namespace: app_test

# production:
#   db: 2
#   host: 127.0.0.1
#   namespace: app_production